environment: qa

backend:
  env:
    CORS_ORIGINS: "https://frontend.qa.comsatel.com.pe"
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging-qa

frontend:
  env:
    VITE_API_URL: https://backend.qa.comsatel.com.pe
    VITE_CUBEJS_API_URL: https://cubejs.qa.comsatel.com.pe/cubejs-api/v1
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging-qa
