environment: prod

backend:
  replicaCount: 2
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

frontend:
  replicaCount: 2
  env:
    VITE_API_URL: https://backend.prod.comsatel.com.pe
    VITE_CUBEJS_API_URL: https://cubejs.prod.comsatel.com.pe/cubejs-api/v1
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
