version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend-app:
    build:
      context: ./dashboard-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./dashboard-app/.env:/app/.env:ro
