apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dashboardstudio.fullname" . }}-frontend-configmap
  labels:
    {{- include "dashboardstudio.labels" . | nindent 4 }}
    component: frontend
data:
  .env: |
    {{- range $key, $value := .Values.frontend.env }}
    {{ $key }}={{ $value | quote }}
    {{- end }}
