"""add execution logging models

Revision ID: fb3010eb1d9a
Revises: caa1490c201a
Create Date: 2026-05-15 12:09:39.492558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb3010eb1d9a'
down_revision: Union[str, Sequence[str], None] = 'caa1490c201a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_history',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('flow_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['biportal.integration_flows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='biportal'
    )
    op.create_table('node_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=50), nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['biportal.execution_history.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='biportal'
    )
    op.drop_index(op.f('idx_if_exec_flow_id'), table_name='integration_flow_executions')
    op.drop_table('integration_flow_executions')
    op.drop_table('alembic_version')
    op.alter_column('color_palettes', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'color_palettes', 'users', ['created_by'], ['id'], source_schema='biportal', referent_schema='biportal')
    op.alter_column('cube_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('cube_config_created_by_fkey'), 'cube_config', type_='foreignkey')
    op.create_foreign_key(None, 'cube_config', 'users', ['created_by'], ['id'], source_schema='biportal', referent_schema='biportal')
    op.alter_column('currencies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('dashboard_assignments_user_id_fkey'), 'dashboard_assignments', type_='foreignkey')
    op.drop_constraint(op.f('dashboard_assignments_dashboard_id_fkey'), 'dashboard_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'dashboard_assignments', 'users', ['user_id'], ['id'], source_schema='biportal', referent_schema='biportal', ondelete='CASCADE')
    op.create_foreign_key(None, 'dashboard_assignments', 'dashboards', ['dashboard_id'], ['id'], source_schema='biportal', referent_schema='biportal', ondelete='CASCADE')
    op.alter_column('dashboards', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('dashboards_created_by_fkey'), 'dashboards', type_='foreignkey')
    op.create_foreign_key(None, 'dashboards', 'users', ['created_by'], ['id'], source_schema='biportal', referent_schema='biportal')
    op.alter_column('data_sources', 'connection_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_constraint(op.f('data_sources_created_by_fkey'), 'data_sources', type_='foreignkey')
    op.create_foreign_key(None, 'data_sources', 'users', ['created_by'], ['id'], source_schema='biportal', referent_schema='biportal')
    op.alter_column('data_types', 'is_builtin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('diagram_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagram_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('dimensional_models', 'is_global',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('dimensional_models_created_by_fkey'), 'dimensional_models', type_='foreignkey')
    op.create_foreign_key(None, 'dimensional_models', 'users', ['created_by'], ['id'], source_schema='biportal', referent_schema='biportal')
    op.alter_column('editor_tools', 'applicable_diagram_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('editor_tools', 'prop_defs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('editor_tools', 'default_props',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('editor_tools', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('editor_tools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_editor_tools_type'), table_name='editor_tools')
    op.add_column('integration_flows', sa.Column('cron_expression', sa.String(length=100), nullable=True))
    op.add_column('integration_flows', sa.Column('log_level', sa.String(length=20), nullable=True))
    op.alter_column('integration_flows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_flows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_integration_flows_status'), table_name='integration_flows')
    op.drop_constraint(op.f('integration_flows_created_by_fkey'), 'integration_flows', type_='foreignkey')
    op.create_foreign_key(None, 'integration_flows', 'users', ['created_by'], ['id'], source_schema='biportal', referent_schema='biportal')
    op.drop_column('integration_flows', 'schedule')
    op.alter_column('knowledge_spaces', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('knowledge_spaces_created_by_fkey'), 'knowledge_spaces', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_spaces', 'users', ['created_by'], ['id'], source_schema='biportal', referent_schema='biportal')
    op.drop_index(op.f('idx_llm_config_provider'), table_name='llm_config')
    op.drop_constraint(op.f('llm_config_created_by_fkey'), 'llm_config', type_='foreignkey')
    op.create_foreign_key(None, 'llm_config', 'users', ['created_by'], ['id'], source_schema='biportal', referent_schema='biportal')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'viewer'::character varying"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_biportal_users_email'), 'users', ['email'], unique=True, schema='biportal')
    op.alter_column('widgets', 'chart_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'bar'::character varying"))
    op.alter_column('widgets', 'position_x',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('widgets', 'position_y',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('widgets', 'position_w',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('6'))
    op.alter_column('widgets', 'position_h',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('widgets', 'use_mock_data',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('widgets_dashboard_id_fkey'), 'widgets', type_='foreignkey')
    op.create_foreign_key(None, 'widgets', 'dashboards', ['dashboard_id'], ['id'], source_schema='biportal', referent_schema='biportal', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'widgets', schema='biportal', type_='foreignkey')
    op.create_foreign_key(op.f('widgets_dashboard_id_fkey'), 'widgets', 'dashboards', ['dashboard_id'], ['id'], ondelete='CASCADE')
    op.alter_column('widgets', 'use_mock_data',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('widgets', 'position_h',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('widgets', 'position_w',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('6'))
    op.alter_column('widgets', 'position_y',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('widgets', 'position_x',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('widgets', 'chart_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'bar'::character varying"))
    op.drop_index(op.f('ix_biportal_users_email'), table_name='users', schema='biportal')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'viewer'::character varying"))
    op.drop_constraint(None, 'llm_config', schema='biportal', type_='foreignkey')
    op.create_foreign_key(op.f('llm_config_created_by_fkey'), 'llm_config', 'users', ['created_by'], ['id'])
    op.create_index(op.f('idx_llm_config_provider'), 'llm_config', ['provider'], unique=False)
    op.drop_constraint(None, 'knowledge_spaces', schema='biportal', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_spaces_created_by_fkey'), 'knowledge_spaces', 'users', ['created_by'], ['id'])
    op.alter_column('knowledge_spaces', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('integration_flows', sa.Column('schedule', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'integration_flows', schema='biportal', type_='foreignkey')
    op.create_foreign_key(op.f('integration_flows_created_by_fkey'), 'integration_flows', 'users', ['created_by'], ['id'])
    op.create_index(op.f('idx_integration_flows_status'), 'integration_flows', ['status'], unique=False)
    op.alter_column('integration_flows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_flows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('integration_flows', 'log_level')
    op.drop_column('integration_flows', 'cron_expression')
    op.create_index(op.f('idx_editor_tools_type'), 'editor_tools', ['type'], unique=True)
    op.alter_column('editor_tools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('editor_tools', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('editor_tools', 'default_props',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('editor_tools', 'prop_defs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('editor_tools', 'applicable_diagram_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_constraint(None, 'dimensional_models', schema='biportal', type_='foreignkey')
    op.create_foreign_key(op.f('dimensional_models_created_by_fkey'), 'dimensional_models', 'users', ['created_by'], ['id'])
    op.alter_column('dimensional_models', 'is_global',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('diagram_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagram_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_types', 'is_builtin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'data_sources', schema='biportal', type_='foreignkey')
    op.create_foreign_key(op.f('data_sources_created_by_fkey'), 'data_sources', 'users', ['created_by'], ['id'])
    op.alter_column('data_sources', 'connection_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_constraint(None, 'dashboards', schema='biportal', type_='foreignkey')
    op.create_foreign_key(op.f('dashboards_created_by_fkey'), 'dashboards', 'users', ['created_by'], ['id'])
    op.alter_column('dashboards', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'dashboard_assignments', schema='biportal', type_='foreignkey')
    op.drop_constraint(None, 'dashboard_assignments', schema='biportal', type_='foreignkey')
    op.create_foreign_key(op.f('dashboard_assignments_dashboard_id_fkey'), 'dashboard_assignments', 'dashboards', ['dashboard_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('dashboard_assignments_user_id_fkey'), 'dashboard_assignments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('currencies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'cube_config', schema='biportal', type_='foreignkey')
    op.create_foreign_key(op.f('cube_config_created_by_fkey'), 'cube_config', 'users', ['created_by'], ['id'])
    op.alter_column('cube_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'color_palettes', schema='biportal', type_='foreignkey')
    op.alter_column('color_palettes', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('integration_flow_executions',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('flow_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('logs', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('result_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('executed_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], name=op.f('integration_flow_executions_executed_by_fkey')),
    sa.ForeignKeyConstraint(['flow_id'], ['integration_flows.id'], name=op.f('integration_flow_executions_flow_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('integration_flow_executions_pkey'))
    )
    op.create_index(op.f('idx_if_exec_flow_id'), 'integration_flow_executions', ['flow_id'], unique=False)
    op.drop_table('node_execution_logs', schema='biportal')
    op.drop_table('execution_history', schema='biportal')
    # ### end Alembic commands ###
