import {
  Activity,
  LayoutGrid,
  Home,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Network,
  Repeat,
  BarChart,
  Settings,
  User,
  Menu,
  Bell,
  LogOut,
  Brush,
  Eye,
  Plus,
  PlusCircle,
  Save,
  X,
  Pencil,
  MoreVertical,
  Box,
  Clock,
  Share2,
  Moon,
  Sun,
  LayoutDashboard,
  Database,
  Mail,
  Zap,
  FileText,
  Brain,
  Sparkles,
  StickyNote,
  Folder,
  GripVertical,
  ZoomOut,
  ZoomIn,
  Grid3X3,
  Focus,
  Palette,
  Info,
  Link,
  AlertTriangle,
  ArrowUpToLine,
  AlignLeft,
  AlignRight,
  Search,
  HelpCircle,
  CheckCircle,
  AlertCircle,
  XCircle
} from 'lucide-vue-next'

export const iconMap = {
  'analytics': Activity,
  'grid_view': LayoutGrid,
  'home': Home,
  'expand_more': ChevronDown,
  'expand_less': ChevronUp,
  'chevron_left': ChevronLeft,
  'chevron_right': ChevronRight,
  'account_tree': Network,
  'sync_alt': Repeat,
  'bar_chart': BarChart,
  'settings': Settings,
  'person': User,
  'menu': Menu,
  'notifications': Bell,
  'logout': LogOut,
  'brush': Brush,
  'visibility': Eye,
  'add': Plus,
  'add_circle': PlusCircle,
  'save': Save,
  'close': X,
  'edit': Pencil,
  'more_vert': MoreVertical,
  'widgets': Box,
  'schedule': Clock,
  'share': Share2,
  'dark_mode': Moon,
  'light_mode': Sun,
  'dashboard': LayoutDashboard,
  'database': Database,
  'email': Mail,
  'transform': Zap,
  'description': FileText,
  'psychology': Brain,
  'auto_awesome': Sparkles,
  'notes': StickyNote,
  'category': Folder,
  'drag_indicator': GripVertical,
  'zoom_out': ZoomOut,
  'zoom_in': ZoomIn,
  'grid_on': Grid3X3,
  'grid_off': Grid3X3,
  'center_focus_strong': Focus,
  'palette': Palette,
  'info': Info,
  'link': Link,
  'warning': AlertTriangle,
  'vertical_align_top': ArrowUpToLine,
  'format_align_left': AlignLeft,
  'format_align_right': AlignRight,
  'search': Search,
  'help': HelpCircle,
  'check_circle': CheckCircle,
  'alert_circle': AlertCircle,
  'x_circle': XCircle
}
